title: Elixon Fredy Nanclares Barbosa
description: Economista | Evaluación de políticas públicas | Economía aplicada
theme: minimal-mistakes-jekyll
url: https://elixonfnanclares.github.io

author:
  name: Elixon Fredy Nanclares Barbosa
  bio: Economista especializado en evaluación de políticas públicas.
  location: Bogotá D.C.
  links:
    - label: ORCID
      url: https://orcid.org/0009-0000-9571-912X
    - label: Google Scholar
      url: https://scholar.google.com/citations?view_op=view_citation&hl=en&user=Mda6WCMAAAAJ&citation_for_view=Mda6WCMAAAAJ:u-x6o8ySG0sC
    - label: SSRN
      url: https://ssrn.com/author=XXXXX
footer:
  links:
    - label: "Licencia del sitio"
      url: https://creativecommons.org/licenses/by-nc/4.0/
